### ISSUE TITLE
SignOut link does not deauthenticate user. 

### ISSUE THREAD

**Issue by fonzi** [uhuraapp/uhura-frontend#120]
When clicking the sign out link, the user does get signed out. 
I am logged in with my user that i signed up with though google +

Server : Localhost with latest git pull.
Firefox build 39
Chrome build 44.0.2403.157 (64-bit)

![1](https://cloud.githubusercontent.com/assets/626330/9570122/55c3a8aa-4f35-11e5-93e4-2ecff17b95d8.png)

Console caught error. 
```
Uncaught Error: Nothing handled the action 'invalidateSession'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.triggerEvent @ ember.debug.js:27690trigger @ ember.debug.js:49702Router.trigger @ ember.debug.js:48461_emberRuntimeSystemObject.default.extend.send @ ember.debug.js:27162_emberMetalMixin.Mixin.create.send @ ember.debug.js:29938_emberMetalMixin.Mixin.create.send @ ember.debug.js:29938runRegisteredAction @ ember.debug.js:22064Backburner.run @ ember.debug.js:284run @ ember.debug.js:19036actions.push.handler @ ember.debug.js:22057(anonymous function) @ ember.debug.js:39893jQuery.event.dispatch @ jquery.js:4670elemData.handle @ jquery.js:4338
```

**Comment by fonzi** [comment]
I may be setting up automation for this types of test. 

@dukex let me know what you think
I can use selenium with java, or ruby. However I am not too familiar with JS. I can give it a shot if you wish to keep the project in pure JS.

**Comment by dukex** [comment]
@fonzi I prefer ruby, because I'm a ruby developer. 

But I need know, it's important in this test using selenium a specific environment with channels, episodes, etc created?  For example, I did a [acceptance test to player](https://github.com/uhuraapp/uhura-frontend/blob/master/tests/acceptance/player-test.js) and I needed [create channels and episodes](https://github.com/uhuraapp/uhura-frontend/blob/master/tests/acceptance/player-test.js#L30-L31) before tests run, like a use ember-cli-qunit I can create the fixtures without touch in a server API and I can [run the tests in CI](https://travis-ci.org/uhuraapp/uhura-frontend). 
How we do this things using selenium?

**Comment by fonzi** [comment]
@dukex 

The selenium framework would not need to touch the CLI if we decide to do so. It would all be front end testing, at the moment as the build stands, we would only be able to test login/logout, unsubscribe and share functionalities. 

Once the searchbar / enter url are implemented then we would add front end test to add channels.

**Comment by dukex** [comment]
@fonzi We need a new repository to upload this tests?

**Comment by fonzi** [comment]
@dukex not unless we want to separate the repositories, I figured when I can I'll just create a new folder inside the app project. 

However we may want to if we are worried about dependences breaking because of one another.

**Comment by dukex** [comment]
OK, fell free to create the new directory and start the tests, I'll learn more about selenium and try to help you
